name: andani_d1_afternoon
channels:
  - defaults
dependencies:
  - python>3.11
  - numpy==1.26.4
  - scipy==1.13.1
  - matplotlib==3.9.2
  - jupyter
  - jupyterlab
  - pip:
    - neo[nixio,nwbio]==0.13.3
    - elephant[extras]==1.1.0
    - viziphant==0.4.0
